### ISSUE TITLE
How to install jpy for snappy?

### ISSUE THREAD

**Issue by j08lue** [senbox-org/snap-engine#101]
I am trying to install `snappy` in OSGeo4W Python (for use with QGIS) on Windows using this approach:

```
snappy-conf <python-exe> <snappy-dir>
``` 

from the [docs](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/50855941/Configure+Python+to+use+the+SNAP-Python+snappy+interface), where `<python-exe>` is OSGeo4W's Python and `<snappy-dir>` is the `site-packages` directory.

`snappy` gets installed fine in `site-packages`, but when I import it, I get

```
C:\>python
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\snappy\__init__.py", line 61, in <module>
    import jpyutil
ImportError: No module named jpyutil
```

I can see there is supposed to be a lot of magic going on in `snappyutil.py` to copy the binary-compiled `jpy` around:

https://github.com/senbox-org/snap-engine/blob/215b01a1a15b518fd7b7fdc189bc7705bdfbdcbc/snap-python/src/main/resources/snappy/snappyutil.py#L65-L87

But somehow it fails. How can I make it happen?

https://github.com/GlobWetlandAfrica/GWA_installer/issues/10

**Comment by j08lue** [comment]
I just found this repo of compiled wheels: https://github.com/senbox-org/snap-engine/tree/master/snap-python/src/main/resources/lib

I guess that is somehow missing when I run `snappy-conf`.

**Comment by j08lue** [comment]
After installing `jpy` from the wheels I found, I am one step further:
```
C:\>python
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\snappy\__init__.py", line 63, in <module>
    jpyutil.preload_jvm_dll()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\jpyutil.py", line 344, in preload_jvm_dll
    return ctypes.CDLL(jvm_dll_file, mode=ctypes.RTLD_GLOBAL)
  File "C:\OSGEO4~1\apps\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

**Comment by j08lue** [comment]
I can see in [`jpyutil.py`](https://github.com/bcdev/jpy/blob/master/jpyutil.py) that it searches in various places for `jvm.dll`, including loads of environment variables etc. 

So what way do you recommend I make QGIS aware of SNAP's JRE? Environment variables?

**Comment by j08lue** [comment]
Turns out when I installed the `jpy` wheel, the setup created a `jpyconfig` file in `site-packages`: `C:\OSGeo4W64\apps\Python27\Lib\site-packages\jpyconfig.py` which has some defaults for the JRE paths:

```
# Created by 'jpyutil.py' tool on 2018-02-08 15:38:39.809000
# This file is read by the 'jpyutil' module in order to load and configure the JVM from Python
java_home = 'C:\\Program Files\\Java\\jdk1.8.0'
jvm_dll = 'C:\\Program Files\\Java\\jdk1.8.0\\jre\\bin\\server\\jvm.dll'
jvm_maxmem = None
jvm_classpath = []
jvm_properties = {}
jvm_options = []
```

Since these are read in `jpyutil.py` and it does not check whether that path even exists, it never gets to the environment variable magic.

**Comment by j08lue** [comment]
One step further:
```
>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\snappy\__init__.py", line 235, in <module>
    jpy.create_jvm(options=_get_snap_jvm_options())
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\snappy\__init__.py", line 201, in _get_snap_jvm_options
    "existing SNAP distribution directory.")
IOError: Can't find SNAP distribution directory. Either configure variable 'snap_home' in file './snappy.ini' or set environment variable 'SNAP_HOME' to an existing SNAP distribution directory.
```

**Comment by j08lue** [comment]
After setting the `SNAP_HOME` environment variable, `snappy` import finally works:
```
>>> import snappy
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
>>> dir(snappy)
['AbstractBand', 'ArrayList', 'Arrays', 'Band', 'Collections', 'ConvolutionFilterBand', 'CrsGeoCoding', 'DefaultGeographicCRS', 'EXCLUDED_DIR_NAMES', 'EXCLUDED_JAR_NAMES', 'EXCLUDED_NB_CLUSTERS', 'Engine', 'EngineConfig', 'FeatureUtils', 'File', 'FlagCoding', 'GPF', 'GeneralFilterBand', 'GeoCoding', 'GeoPos', 'Geometry', 'HashMap', 'HashSet', 'List', 'ListFeatureCollection', 'Map', 'Mask', 'Operator', 'PixelGeoCoding', 'PixelGeoCoding2', 'PixelPos', 'PlainFeatureFactory', 'Point', 'Product', 'ProductData', 'ProductIO', 'ProductNodeGroup', 'ProductUtils', 'ProgressMonitor', 'RasterDataNode', 'Rectangle', 'Set', 'SimpleFeatureBuilder', 'String', 'SystemUtils', 'TiePointGeoCoding', 'TiePointGrid', 'Tile', 'VectorDataNode', 'VirtualBand', 'WKTReader', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '_get_nb_user_modules_dir', 'annotate_RasterDataNode_methods', 'called_from_java', 'config', 'cp', 'debug', 'glob', 'jpy', 'jpyutil', 'module_dir', 'module_ini', 'os', 'snap_home', 'start_snap_engine', 'sys']
>>> snappy.start_snap_engine
True
```

**Comment by j08lue** [comment]
Even though I found a workaround, my issue is not really resolved - why did the auto-configuration not work in my case?

**Comment by marpet** [comment]
snappy wasn't developed with the intention in mind to work within the OSGEO/QGIS environment. So I'm not surprised the problems occur. I don't know why the auto-configuration didn't work for you. I don't know the OSGEO/QGIS environment. Finally you made it, which is great, but I can't deep dive into this environment and find out why it is not working. However, you might be pleased if you hear that we are working on enhancements regarding the installation of snappy and jpy. But till this gets released it will take a while. Maybe in the second half of this year.

**Comment by j08lue** [comment]
OK, thanks for the heads-up, @marpet.
