### ISSUE TITLE
Nodata band when use Radiometric terrain flattening on ENVISAT 2010 product

### ISSUE THREAD

**Issue by FZaf** [senbox-org/snap-engine#111]
Goodmorning, 
i would elaborate a 2010 ENVISAT product; i activate Debrust and calibration, system creates sigma HH bands, than i convert each Sigma band into beta0 band and execute the Radiometric terrain flattening; only the first band works, other bands are full of nodata values.
I miss something or it's a problem (maybe due to the old dataset i used)?
thanks
Francesco

**Comment by marpet** [comment]
This issue was moved to senbox-org/s1tbx#51

**Comment by marpet** [comment]
I moved this issue into the S1TBX because your issue deals with SAR data.
