### ISSUE TITLE
Snappy subset inconsistency

### ISSUE THREAD

**Issue by Ixiodor** [senbox-org/snap-engine#112]
The problem is:
```
        print("creating subset ...")
        params = HashMap()
        params.put('region', "%s,%s,%s,%s" % (0, 0, 600, 600))
        subset = snap.GPF.createProduct('Subset', params, resampled)
```
Works fine.

This dosn't:
```
        print("creating subset ...")
        params = HashMap()
        params.put('region', "%s,%s,%s,%s" % (0, 0, 580, 720))
        subset = snap.GPF.createProduct('Subset', params, resampled)
```

Seems like image get stretched on eache iteration(600, 599 - produce better results but sliced in the middle)

**Comment by marpet** [comment]
Could you provide some more information, please?
How big is the resampled product? How differ the results of the two runs?
What do you mean by 'each iteration'? Why is the resulting image stretched? Maybe you can 
attach some images to explain the problem?

**Comment by marpet** [comment]
Sorry, I haven't noticed that you already replied.
I tried to replicate what you are doing: I used the following script. (I had to rename it to *.txt)
[resample_iteration.txt](https://github.com/senbox-org/snap-engine/files/2277960/resample_iteration.txt)

That's the result:
![image](https://user-images.githubusercontent.com/204590/43959223-644311d0-9cae-11e8-9058-535c4a071d6e.png)

**Comment by marpet** [comment]
Shouldn't be closed.

**Comment by Ixiodor** [comment]
You are right, saving dataset get correct data. The problem is "getBand" without write product.
If you add:

> red = subset3.getBand('B4')
red_data = np.zeros((red.getRasterWidth(), red.getRasterHeight()), dtype=np.float32)
red_data = red.readPixels(0, 0, red.getRasterWidth(), red.getRasterHeight(), red_data)
plt.imsave(os.path.join("out", '{}.png'.format("te")), red_data, cmap='Greys')

You'll get wrong data

**Comment by Ixiodor** [comment]
Ok, i found the problem. My mistake. Widht and Height was swapped, so saving was getting visual errors by pixel shift.
Thanks for you help and time.

**Comment by marpet** [comment]
Your welcome.
