### ISSUE TITLE
How can I limit SNAP usage of cpu

### ISSUE THREAD

**Issue by Mvpl** [senbox-org/snap-engine#114]
I would like to know how can I limit SNAP usage of cpu (via command line) because right now it is consuming every cpu I add to my machine.

**Comment by marpet** [comment]
For a single gpt call you can the '-q' option.
`gpt -q 7 ...`
This limits the number of threads (processors) to 7. 
Type `gpt --diag` to get the default number of threads. Choose any number lower then what is printed.

If you want to limit the number of used processors in general, for SNAP Desktop and gpt you can edit the snap.properties file which is located in the etc folder of the installation directory.
Look out for the following section.
```
# number of CPU cores used for image rendering and graph processing
# allow this to default to Runtime.getRuntime().availableProcessors()
#snap.parallelism = 1
```
Remove the leading # and change the number e.g.:
snap.parallelism = 9

You could have asked the question also in our forum at https://forum.step.esa.int/
If you don't know it yet.
