### ISSUE TITLE
Problematic installation on Ubuntu/Linux with miniconda3

### ISSUE THREAD

**Issue by elmerehbi** [senbox-org/snap-engine#116]
I have noticed that the installation of snappy is being problematic for several.
I have written a script and shared it as a [gist](https://gist.github.com/elmerehbi/522b756f5c8ad8e5105323ef66914aa0) however I would appreciate your and especially the developers feedback.

**Comment by elmerehbi** [comment]
As I mention I have seen and personally faced problems in the installation process of snappy. In particular, it has to do with the `jpy` package. With this gitst I was able to get snappy to import with Python 3.4 (not 3.6 or 3.7) in a miniconda environment. The comment below the gist also mentions that importing jpy before importing snappy fails.

**Comment by marpet** [comment]
Thanks again, for your input elmerehbi.
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net). This one can be found here: [SNAP-1043](https://senbox.atlassian.net/browse/SNAP-1043)

So please come to the forum if you have want to share something else.
