### ISSUE TITLE
Conflict with other snappy modules

### ISSUE THREAD

**Issue by elmerehbi** [senbox-org/snap-engine#121]
It seems there are multiple other Python modules named `snappy`.

On two occasions I tried importing python modules which use one of those snappy modules and it fails because snap-python overrides them.

Take the following example:

```
import xarray
```
which results in

    AttributeError: module 'snappy' has no attribute 'compress'

**Comment by marpet** [comment]
Thanks for the info.
It is already considered in our [JIRA issue tracker](https://senbox.atlassian.net/browse/SNAP-937)
