### ISSUE TITLE
progress when using gpt command line

### ISSUE THREAD

**Issue by skluz** [senbox-org/snap-engine#53]
I wonder if it's possible to see processing progress during gpt usage. When processing large images I do not know what is happening. I'm not talking about precise percentage progress - just for example: 

gpt.exe long-processing.xml
...
- Apply-Orbit-File step 4 of 17 started
- TOPSAR-Deburst(3) step 5 of 17 started
  ...
- TOPSAR-Deburst(3) step 5 of 17 finished in 200 seconds
  ..

Would it be possible to implement such feature?

**Comment by marpet** [comment]
We have an issue for this
https://senbox.atlassian.net/browse/SNAP-650
