### ISSUE TITLE
Error in Inport-Vector module

### ISSUE THREAD

**Issue by claudiodp** [senbox-org/snap-engine#55]
Hello,

I'm making a new graph builder but I get the following error:

"_Error in graph: [Node:Import-Vector] Operator 'ImportVectorOp': Mandatory source product (field 'sourceProduct') not set._" 

But I selected the correct one!
Could you help me?

Thank you in advance.
Claudio

**Comment by marpet** [comment]
Could you ask this question in the [forum](http://forum.step.esa.int/) again please. 
It is better suited there. Also a bit more information on how you have configured the graph would be helpful.

Thanks
