### ISSUE TITLE
Lack of expressions examples in documentation (BandMathsOp.BandDescriptor)

### ISSUE THREAD

**Issue by kedziorm** [senbox-org/snap-engine#57]
As a snappy-python user I would like to know how to perform bands calculations using bands stored in two different Sentinel/SMOS/other products.

Unfortunately there are no examples of correct expressions within the documentation and examples.
Documentation says only that expression is of string type:

http://step.esa.int/docs/v2.0/apidoc/engine/org/esa/snap/core/gpf/common/BandMathsOp.BandDescriptor.html#expression

**Comment by TonioF** [comment]
I just answered to this in the STEP forum ( http://forum.step.esa.int/t/calculate-the-difference-or-division-between-bands-in-two-different-products/2684 ):
"The correct way to form this expression is: band + ' - $sourceProduct.1.' + band
Note that the index is zero-based, so index 1 refers to the second product. I also noticed you only pass one product when calling the GPF. You should pass the whole array.

You may also put the source products in a map and assign names to them in that fashion, e.g.: 
productMap = HashMap()
productMap.put('numberOne', product1);
productMap.put('numberTwo', product2);
The expression would then look like this: band + ' - $numberTwo.' + band"

**Comment by TonioF** [comment]
...but as your question here is more directed at the missing documentation: An example is actually given in the description of the BandMathsOp: http://step.esa.int/docs/v2.0/apidoc/engine/org/esa/snap/core/gpf/common/BandMathsOp.html
It's of no help though, as the syntax is slightly different.
I'll change that.
