### ISSUE TITLE
"No SPI found for operator name" when trying an example plugin

### ISSUE THREAD

**Issue by apala-unica-it** [senbox-org/snap-engine#65]
After building and installing the plugins supplied as examples, when trying to launch them,  the following exception occurs:

```
java.lang.IllegalArgumentException: No SPI found for operator name 'MyOp'
	at org.esa.snap.core.gpf.ui.DefaultSingleTargetProductDialog.<init>(DefaultSingleTargetProductDialog.java:78)
	...

```
This happens for both the Java and the Python example operator plugins.
(Actually, the Python plugin works as long as no other example plugins are installed).

![error1](https://cloud.githubusercontent.com/assets/23053167/19684378/2aaa4718-9ab7-11e6-81fb-034cef35151b.png)

**Comment by marpet** [comment]
Do you have a SPI in META-INF/services?
Do you let you Operator run on an installed SNAP or do you build SNAP from sources?

**Comment by apala-unica-it** [comment]
> Do you have a SPI in META-INF/services?

I'm using the provided sources. The Java operator contains its META-INF/services/org.esa.snap.core.gpf.OperatorSpi file; the Python operator has its own META-INF/services/org.esa.snap.python.gpf.PyOperatorSpi file.

> Do  you let you Operator run on an installed SNAP or do you build SNAP from sources?

I've tried with both configurations: binary SNAP (4.1.0) and built from source (5.0.0).

**Comment by marpet** [comment]
And you have updated the OperatorSPI and PyOperatorSpi files?
In the layer.xml, do you use the same name for the operator as in the OperatorMetadata annotation respectively the *-info.xml?

I think it would be easier to help if you could share the code.

**Comment by apala-unica-it** [comment]
I think I actually have two separate issues here.

With SNAP 4.1.0 (binary distribution) I can install and launch the example Python plugin, but not one I modified. I cannot install the example Java plugin since it requires the 5.0 version of the engine.

With SNAP 5.0.0 (compiled from source) I cannot launch either the Java plugin template, or the Python example plugin. But this could be due to some build problem on my side.

Since my problem seems to be limited to the Python side, I will close this issue and open a more specific one.
