### ISSUE TITLE
readGeoTIFFProduct from GeoTiffProductReader

### ISSUE THREAD

**Issue by kristenstewert11** [senbox-org/snap-engine#71]
dear sir：
“readGeoTIFFProduct” from this class is invisible in other package，how can I use this methods in other package ？

**Comment by TonioF** [comment]
Dear Kristen,

this sort of question is best asked in the forum: http://forum.step.esa.int 

The reading of products is usually handled by the ProductIO, so you can use

ProductIO.readProduct(File file, "GeoTIFF") (you may omit the second parameter)

If you want to use the GeoTiffProductReader directly, use

reader.readProductNodes(Object input, ProductSubsetDef subsetDef) (first parameter can be String, File or InputStream, second parameter can be null)
