### ISSUE TITLE
dowloading freeze

### ISSUE THREAD

**Issue by oceanographist** [senbox-org/snap-engine#73]
When I install engine, it freezes in this line:
Downloading: http://nexus.senbox.net/nexus/content/repositories/public/com/sun/media/jai-imageio/1.2-SNAP-20150402/jai-imageio-1.2-SNAP-20150402.jar
465/818 KB 

what should I do to get over this?

ps. same problem for snap-desktop (1) and sen2coral(2)
(1)Downloaded: http://nexus.senbox.net/nexus/content/repositories/public/org/esa/snap/snap-core/6.0.0-SNAPSHOT/snap-core-6.0.0-20170118.190425-28.jar (1474 KB at 753.7 KB/sec)

(2)Downloaded: http://nexus.senbox.net/nexus/content/repositories/public/org/esa/snap/snap-gpf/6.0.0-SNAPSHOT/snap-gpf-6.0.0-20170118.190446-28.jar (453 KB at 433.1 KB/sec)

**Comment by marpet** [comment]
Some times it helps to execute the maven command several times. Especially if you build SNAP for the first time and maven need to download many libraries. I just checked our server, where the libraries are located, it seems to be healthy.

**Comment by oceanographist** [comment]
I executed it 33 times and keep trying. It stucked in the same file in every attempt.

**Comment by marpet** [comment]
Can you download those files manually? Just to know if it works.

**Comment by oceanographist** [comment]
It has the same problem on web browser, as well. I am going to change my internet connection network and try again.

**Comment by oceanographist** [comment]
It is ok now. The problem was due to internet connection network. For your information

**Comment by marpet** [comment]
OK. Good to hear that it now works.
