### ISSUE TITLE
Resampling and subsetting S2 scene and saving as GeoTIFF-BigTIFF does not work

### ISSUE THREAD

**Issue by radosuav** [senbox-org/snap-engine#75]
Hi,

Running a simple graph to resample and subset a S2 scene (Read  > Resample > Subset > Write) works only if the output is saved as BEAM-DIMAP. If I change the output to GeoTIFF-BigTIFF (or other format) I get an error message("Error: [NodeId: Write] Product writer is unable to write this product as 'GeoTIFF-BigTIFF': Cannot write multisize products. Consider resampling the product first"). However, if I first run a resampling graph (Read  > Resample > Write) with output saved as BEAM-DIMAP and then use this output as input to a subset graph (Read  > Subset > Write) and save the second output as GeoTIFF-BigTIFF then it works fine. 

I am using SNAP 5.0.1 and S2TBX 5.0.1 and as input I use S2A_OPER_PRD_MSIL1C_PDMC_20161129T230905_R051_V20161127T105402_20161127T105402.SAFE scene. I don't remember experiencing this issue in SNAP 5.0.0.

**Comment by radosuav** [comment]
@lveci, @marpet is this a know issue with SNAP 5.0.1? Or maybe something local on my computer?

**Comment by marpet** [comment]
I haven't heard about it before. But I don't work that much with S2 data currently.
However, such questions are better suited in our [forum](http://forum.step.esa.int). More users can read it and help you further.

**Comment by radosuav** [comment]
Ok thanks, I'll write to the forum. But to me it seems more like a bug that should be reported to the developers rather then an user issue to be discussed on the forum.

**Comment by marpet** [comment]
We are also active on the forum and turn such reports into tickets in our issue system.
Even if it is a bug it is good if the users know bout it. So it's good to discuss it there.
