### ISSUE TITLE
GeoTIFF-BigTIFF writer is very slow

### ISSUE THREAD

**Issue by radosuav** [senbox-org/snap-engine#76]
Saving an output of a subset graph (Read > Subset > Write) as a GeoTIFF-BigTIFF  is very slow (2.6 minutes, 259 B/s, 128 pixels/s) even though the output is only 2 bands and 100x100 pixels (29 MB). 

Changing the output format to GeoTIFF (or to other formats) and keeping all the other parameters the same speeds things up significantly (3 seconds, 13504 B/s, 6666 Pixels/s).

Tested on SNAP 5.0.1 with a S2 scene previously resampled to 60 m.

**Comment by radosuav** [comment]
It only seems to be the case when copy metatada is set to true in the Subset operator. When it is set to false then writing of GeoTIFF-BigTIFF is as fast as for other formats.

**Comment by marpet** [comment]
Turned into an issue in our tracking system.
https://senbox.atlassian.net/browse/SNAP-685
