### ISSUE TITLE
catchOperatorException makes working out what went wrong difficult 

### ISSUE THREAD

**Issue by wselwood** [senbox-org/snap-engine#95]
We have be tracking around a problem in the `RangeDopplerGeocodingOp` class this morning and run into a problem. The method in question is wrapped in a try catch(throwable) that is using the `OperatorUtils.catchOperatorException` function. This throws away the stack trace of the actual error and just keeps the generic "java.lang.NullPointerException" message which is not useful for working out what happened. 

https://github.com/senbox-org/snap-engine/blob/master/snap-engine-utilities/src/main/java/org/esa/snap/engine_utilities/gpf/OperatorUtils.java#L417

I'd suggest either adding the incoming throwable as a caused by on the thrown `OperatorException` or trying to remove uses of that function as it makes things really hard to trace.

```
throw new OperatorException(message, e);
```

**Comment by forman** [comment]
I fully agree. OperatorExceptions should never be swallowed.

**Comment by wselwood** [comment]
I'm happy to create the 2 character pr if wanted. I'll just need a little while to get the build set up on my machine

**Comment by marpet** [comment]
Your welcome
