### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by fresm** [senbox-org/snap-engine#97]
@marpet What's the exact command to compile this software under Linux (with maven)?

**Comment by marpet** [comment]
You can find the information in the development guide:[How to build SNAP from sources](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/10879039/How+to+build+SNAP+from+sources)
It is linked in the [Readme.md](https://github.com/senbox-org/snap-engine/blob/master/README.md)

**Comment by fresm** [comment]
Thanks for the answer.

After installing the snap-toolbox via the [bash script](http://step.esa.int/downloads/6.0/installers/esa-snap_all_unix_6_0.sh) I'm getting an error: 

> Unable to initialize WWWorldMapToolView: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped

**Comment by marpet** [comment]
Is your Linux running in a VM? Which Linux do you use?
Maybe you can update the graphics card driver or enable 3D support.
Maybe this [post in our forum](http://forum.step.esa.int/t/snap-5-0-fails-to-launch-on-linux/5613/2?u=marpet) helps you.

**Comment by fresm** [comment]
I'm using ArchLinux with a RX 460 graphics card and the latest (-git) radeonsi drivers
